// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/@tanstack_react-query/index.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/react-hook-form/index.tsx";
import * as $$0 from "./islands/Island-react-hook-form.tsx";
import * as $$1 from "./islands/Island@tanstack_react-query.tsx";

const manifest = {
  routes: {
    "./routes/@tanstack_react-query/index.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/react-hook-form/index.tsx": $2,
  },
  islands: {
    "./islands/Island-react-hook-form.tsx": $$0,
    "./islands/Island@tanstack_react-query.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
